language: java
jdk:
- oraclejdk8
notifications:
  slack: dptinfo-utln:ubR1XWExIdQfS3oI783vSxJx
# TODO: Hack until Travis support setting maven version or upgrades
before_install:
  - wget http://mirrors.ircam.fr/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
before_script:
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r

script: mvn verify -Dgpg.skip=true
branches:
    only:
        - master
        - development